"use client";
import { FormEvent, useState } from "react";
type Message={from:"bot"|"user";text:string};
const answers:Record<string,string>={
  experience:"Richmond has more than 15 years of professional experience and has served as Head of Finance at the Nursing & Midwifery Training College, Atibie since 2013.",
  qualifications:"He is a Chartered Accountant (ICAG), an ISO Lead Auditor, and holds an MBA in Accounting & Finance and an HND in Accounting. He completed a Cybersecurity GRC & IT Audit programme in 2026.",
  projects:"Featured work includes an institutional financial management system, CyberSecure360, a water-production business case and research on responsible AI in public-sector accounting.",
  cybersecure:"CyberSecure360 is Richmond’s unified GRC and security-operations platform concept. It includes executive KPIs, enterprise risk and heat maps, incidents, vulnerabilities, assets, controls, evidence, audits, third-party risk, BIA/BCP/DR, remediation, reports, multi-organization RBAC and mappings for ISO 27001, NIST, CIS, COBIT, PCI DSS, ISO 22301 and the NIST AI RMF.",
  skills:"His capabilities include reporting, budgeting, treasury, tax, audit coordination, internal controls, business analytics, ISO/IEC 27001, NIST CSF 2.0, COBIT, business continuity and AI governance.",
  contact:"Use the WhatsApp, Email or Contact options to start a professional conversation with Richmond."
};
function reply(q:string){const t=q.toLowerCase();if(/cybersecure|cyber secure|dashboard|heat map|incident|vulnerabilit|framework/.test(t))return answers.cybersecure;if(/experience|career|work|role|finance/.test(t))return answers.experience;if(/qualification|education|degree|mba|chartered|certificate/.test(t))return answers.qualifications;if(/project|platform|system/.test(t))return answers.projects;if(/skill|grc|audit|analytics|risk/.test(t))return answers.skills;if(/contact|whatsapp|connect|hire/.test(t))return answers.contact;return "I can help with Richmond’s experience, qualifications, CyberSecure360, projects, skills or contact options."}
export default function ChatBox(){const[open,setOpen]=useState(false);const[input,setInput]=useState("");const[messages,setMessages]=useState<Message[]>([{from:"bot",text:"Hello! I’m Richmond’s portfolio assistant. What would you like to know?"}]);const ask=(label:string,key:string)=>setMessages(c=>[...c,{from:"user",text:label},{from:"bot",text:answers[key]}]);function submit(e:FormEvent){e.preventDefault();const q=input.trim();if(!q)return;setMessages(c=>[...c,{from:"user",text:q},{from:"bot",text:reply(q)}]);setInput("")}return <div className="chat-widget">{open&&<section className="chat-panel" aria-label="Portfolio assistant" aria-live="polite"><header className="chat-header"><div><span className="chat-avatar">RKS</span><p><strong>Portfolio Assistant</strong><small><i/> Online now</small></p></div><button onClick={()=>setOpen(false)} aria-label="Close chat">×</button></header><div className="chat-body">{messages.map((m,i)=><div className={`chat-message ${m.from}`} key={i}>{m.text}</div>)}<div className="chat-suggestions"><button onClick={()=>ask("Experience","experience")}>Experience</button><button onClick={()=>ask("Qualifications","qualifications")}>Qualifications</button><button onClick={()=>ask("CyberSecure360","cybersecure")}>CyberSecure360</button><button onClick={()=>ask("Key projects","projects")}>Key projects</button><button onClick={()=>ask("Core skills","skills")}>Core skills</button></div></div><form className="chat-form" onSubmit={submit}><label className="sr-only" htmlFor="chat-question">Ask a question</label><input id="chat-question" value={input} onChange={e=>setInput(e.target.value)} placeholder="Ask about Richmond…"/><button type="submit" aria-label="Send message">➤</button></form><p className="chat-note">Instant answers based on this portfolio</p></section>}<button className={`chat-launcher ${open?"active":""}`} onClick={()=>setOpen(!open)} aria-label={open?"Close instant chat":"Open instant chat"} aria-expanded={open}><span>{open?"×":"✦"}</span>{!open&&<b>Chat with my portfolio</b>}<i/></button></div>}
