"use client";
import { useState } from "react";

const moduleGroups: Record<string, string[]> = {
  Governance: ["Executive command centre", "Enterprise risk register", "Security control library", "Compliance assessments", "Audit management", "Evidence management"],
  Operations: ["Incident management", "Vulnerability management", "Cyber asset register", "Problem management", "Remediation tracking", "Audit trail"],
  Resilience: ["Business impact analysis", "Business continuity planning", "Disaster recovery", "Crisis readiness", "Backup assurance", "Recovery testing"],
  Assurance: ["Third-party risk", "Cloud security", "Network security", "Application security", "AI governance", "Reports & analytics"],
};

const frameworks = [
  ["ISO/IEC 27001:2022", "Information security management"], ["NIST CSF 2.0", "Govern, Identify, Protect, Detect, Respond, Recover"],
  ["NIST SP 800-53", "Security and privacy controls"], ["CIS Controls v8", "Prioritised cyber safeguards"],
  ["COBIT 2019", "Enterprise governance of information and technology"], ["PCI DSS", "Payment-card security"],
  ["ISO 22301", "Business continuity management"], ["NIST AI RMF", "Responsible artificial-intelligence risk"],
];

export default function CyberSecure360(){
  const [active,setActive]=useState("Governance");
  return <section className="cyber-section" id="cybersecure360"><div className="shell">
    <div className="cyber-intro"><div><p className="section-no cyber-kicker">04 / FLAGSHIP GRC PROJECT</p><h2>CyberSecure<span>360</span></h2><p className="cyber-subtitle">A unified cybersecurity governance, risk, compliance and operations platform.</p></div><div className="cyber-summary"><p>Conceived and developed by Richmond Kwadwo Sarpong to give executives, risk owners, auditors and security teams one reliable view of cyber posture, compliance, resilience and accountable action.</p><div className="cyber-badges"><span>Multi-organization</span><span>Role-based</span><span>Audit-ready</span><span>Executive reporting</span></div><a className="button primary" style={{marginTop:18}} href="./pci-dss/">Launch PCI DSS Dashboard <b>↗</b></a></div></div>
    <div className="command-centre"><div className="command-head"><div><small>EXECUTIVE COMMAND CENTRE</small><h3>Security posture overview</h3></div><span className="live-pill"><i/> Demonstrator</span></div><div className="cyber-kpis"><article><small>OPEN RISKS</small><strong>24</strong><span>5 high priority</span></article><article><small>CRITICAL VULNERABILITIES</small><strong>07</strong><span>3 overdue</span></article><article><small>OPEN INCIDENTS</small><strong>09</strong><span>2 under investigation</span></article><article><small>CONTROL EFFECTIVENESS</small><strong>86%</strong><span>Across mapped controls</span></article></div>
      <div className="cyber-dashboard"><div className="heat-panel"><div className="panel-title"><b>Enterprise risk heat map</b><span>Likelihood × Impact</span></div><div className="heatmap" aria-label="Five by five illustrative risk heat map">{Array.from({length:25},(_,i)=><i key={i} className={`heat h${Math.floor(i/5)}`}>{[3,7,1,4,2,6,2,5,1,3,4,1,6,2,3,1,3,2,4,1,2,1,3,1,2][i]}</i>)}</div></div><div className="framework-progress"><div className="panel-title"><b>Framework readiness</b><span>Illustrative assessment view</span></div>{[["ISO 27001",84],["NIST CSF",78],["CIS Controls",72],["COBIT",68]].map(([name,value])=><div className="progress-row" key={String(name)}><div><span>{name}</span><b>{value}%</b></div><i><em style={{width:`${value}%`}}/></i></div>)}</div><div className="activity-panel"><div className="panel-title"><b>Priority activity</b><span>Action tracking</span></div><ul><li><i className="critical"/><span><b>Access review overdue</b><small>Identity & access management</small></span></li><li><i className="warning"/><span><b>DR exercise scheduled</b><small>Business resilience</small></span></li><li><i className="good"/><span><b>Evidence approved</b><small>ISO 27001 assessment</small></span></li></ul></div></div>
    </div>
    <div className="cyber-modules"><div className="module-copy"><p className="section-no cyber-kicker">PLATFORM COVERAGE</p><h3>From board oversight to operational response.</h3><p>CyberSecure360 connects governance and day-to-day security work so risks, controls, incidents, evidence and improvement actions remain traceable.</p><div className="module-tabs" role="tablist" aria-label="CyberSecure360 module groups">{Object.keys(moduleGroups).map(group=><button key={group} role="tab" aria-selected={active===group} className={active===group?"active":""} onClick={()=>setActive(group)}>{group}</button>)}</div></div><div className="module-list" role="tabpanel"><p>{active} modules</p>{moduleGroups[active].map((item,i)=><article key={item}><span>{String(i+1).padStart(2,"0")}</span><b>{item}</b><i>↗</i></article>)}</div></div>
    <div className="frameworks"><div className="framework-title"><p className="section-no cyber-kicker">CONTROL MAPPING</p><h3>One control, multiple frameworks.</h3><p>Common safeguards can be mapped once and reused across regulatory, governance, resilience and AI-risk obligations.</p></div><div className="framework-grid">{frameworks.map(([name,copy])=><article key={name}><span>✓</span><div><b>{name}</b><p>{copy}</p></div></article>)}</div></div>
    <div className="cyber-workflow"><div><p className="section-no cyber-kicker">CONNECTED WORKFLOW</p><h3>Identify. Assign. Evidence. Assure.</h3></div><ol><li><span>01</span><b>Record</b><p>Capture risks, assets, vulnerabilities, incidents and third parties.</p></li><li><span>02</span><b>Assess</b><p>Score exposure and evaluate mapped framework controls.</p></li><li><span>03</span><b>Treat</b><p>Assign owners, due dates, remediation actions and approvals.</p></li><li><span>04</span><b>Report</b><p>Track posture, overdue work, trends and assurance evidence.</p></li></ol></div>
    <div className="architecture-note"><div><span>PROTOTYPE</span><p>Responsive front-end demonstrator with dashboards, risk visualisation, incident register, CSV export, document templates and light/dark themes.</p></div><i>→</i><div><span>PRODUCTION ROADMAP</span><p>PostgreSQL, authenticated multi-client organizations, granular RBAC, SSO/MFA, encrypted evidence, immutable audit logs, API security, backups and server-side reporting.</p></div></div>
  </div></section>;
}
