import ChatBox from "./ChatBox";
import WhatsAppButton from "./WhatsAppButton";
import EmailButton from "./EmailButton";
import CyberSecure360 from "./CyberSecure360";

const capabilities = ["Financial reporting & decision support", "Budgeting, forecasting & cash flow", "Treasury, tax & statutory compliance", "External audit coordination", "Internal controls & PFM compliance", "Business analytics & dashboards", "Cybersecurity GRC & IT audit", "ISO/IEC 27001:2022", "NIST CSF 2.0 & SP 800-53", "COBIT 2019", "Third-party risk", "Business continuity & disaster recovery", "AI governance & model risk", "Team leadership"];

const projects = [
  { tag: "FINANCE TRANSFORMATION", title: "Institutional Financial Management System", copy: "Designed an integrated operating model for cash books, assets, inventory, suppliers, creditors, commitments, withholding taxes, contracts and executive reporting.", accent: "gold", impact: "Control · Visibility · Accountability" },
  { tag: "CYBERSECURITY GRC", title: "CyberSecure360 Platform", copy: "Developed the concept for a multi-organization platform covering RBAC, framework mapping, compliance assessments, evidence, risk heat maps, audits, BIA/BCP/DR, vendor risk and reports.", accent: "mint", impact: "ISO · NIST · CIS · COBIT" },
  { tag: "STRATEGY & GROWTH", title: "Water Production Business Case", copy: "Advised management on a sachet-water production plant serving students and the surrounding community, linking demand, cost, control and revenue considerations.", accent: "blue", impact: "Analysis · Growth · Community value" },
  { tag: "RESEARCH", title: "AI in Public-Sector Accounting", copy: "Research focus on responsible AI as a route to stronger financial accountability, efficiency and decision-making in Ghana’s public health sector.", accent: "rose", impact: "AI governance · Public value" },
];

const credentials = [
  ["2026", "Cybersecurity GRC & IT Audit Program", "Yesyoucan Cybersecure LLC · Dallas, Texas"],
  ["Current", "ISO Lead Auditor", "Professional certification"],
  ["2022", "MBA, Accounting & Finance", "University of Professional Studies, Accra"],
  ["2018", "Chartered Accountant", "Institute of Chartered Accountants, Ghana"],
  ["2008", "HND, Accounting", "Koforidua Technical University"],
];

export default function Home() {
  return <main>
    <nav className="nav shell" aria-label="Main navigation"><a className="brand" href="#top"><span>RKS</span><b>Richmond Sarpong</b></a><div className="navlinks"><a href="#profile">Profile</a><a href="#experience">Experience</a><a href="#work">Portfolio</a><a href="#cybersecure360">CyberSecure360</a><a href="#credentials">Credentials</a><a className="nav-cta" href="#contact">Let&apos;s connect</a></div></nav>
    <section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow"><span/> FINANCE LEADERSHIP · ANALYTICS · GRC</p><h1>Turning financial insight into <em>trusted decisions.</em></h1><p className="lead">Chartered Accountant, Head of Finance, ISO Lead Auditor and cybersecurity GRC practitioner helping institutions strengthen accountability, resilience and performance.</p><div className="hero-actions"><a className="button primary" href="#work">View selected work <b>↗</b></a><a className="button secondary" href="#credentials">Explore credentials</a></div><div className="proof"><div><strong>15+</strong><span>Years&apos; experience</span></div><div><strong>CA</strong><span>ICAG qualified</span></div><div><strong>MBA</strong><span>Accounting &amp; Finance</span></div><div><strong>GRC</strong><span>IT audit &amp; risk</span></div></div></div>
      <aside className="hero-card" aria-label="Professional focus"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><div className="monogram">RKS</div><p>LEADERSHIP AT THE INTERSECTION OF</p><h2>Finance<br/><span>×</span> Technology<br/><span>×</span> Governance</h2><div className="location">◆ Atibie, Kwahu · Ghana · Global outlook</div></aside></section>
    <section className="marquee" aria-label="Areas of expertise"><div>FINANCIAL LEADERSHIP <i>◆</i> PUBLIC FINANCIAL MANAGEMENT <i>◆</i> BUSINESS ANALYTICS <i>◆</i> CYBERSECURITY GRC <i>◆</i> AI GOVERNANCE</div></section>
    <section className="section shell two-col" id="profile"><div><p className="section-no">01 / EXECUTIVE PROFILE</p><h2>Clarity, control and public value.</h2></div><div className="body-copy"><p>I am Richmond Kwadwo Sarpong, a Ghanaian Chartered Accountant and finance leader with more than 15 years of professional experience and over a decade as Head of Finance in the public health training sector.</p><p>I lead reporting, budgeting, treasury, reconciliations, tax and statutory compliance, audit coordination, internal controls and finance-team delivery. My expanding work in business analytics, cybersecurity GRC, IT audit and responsible AI brings a technology-risk perspective to financial leadership.</p><div className="availability"><span className="pulse"/> Open to senior finance, decision-support, business analytics, GRC and employer-sponsored international opportunities</div></div></section>
    <section className="section dark" id="experience"><div className="shell"><p className="section-no light">02 / LEADERSHIP EXPERIENCE</p><div className="experience-grid"><article className="feature-role"><p>2013 — PRESENT</p><h2>Head of Finance</h2><h3>Nursing &amp; Midwifery Training College, Atibie</h3><p>Serve as principal financial adviser to management, overseeing accurate reporting, budgets, cash and treasury activity, statutory obligations, audits, controls and team performance. Translate financial evidence into practical recommendations for institutional decisions.</p><div className="role-tags"><span>Management reporting</span><span>Budget ownership</span><span>Audit coordination</span><span>PFM compliance</span></div></article><div className="responsibilities"><h3>Leadership scope</h3><ul><li>Monthly, quarterly and annual reporting</li><li>Budgets, forecasts and variance analysis</li><li>Banking, treasury and cash-flow oversight</li><li>VAT, PAYE, withholding tax and SSNIT compliance</li><li>External audit and internal-control coordination</li><li>Procurement, stores and asset-control oversight</li><li>Financial policy, risk and management advice</li><li>Finance staff supervision and capacity building</li></ul></div></div></div></section>
    <section className="section shell" id="work"><p className="section-no">03 / SELECTED PORTFOLIO</p><div className="section-heading"><h2>Work designed for impact.</h2><p>Initiatives combining financial stewardship, technology, governance and responsible innovation.</p></div><div className="projects">{projects.map((p,i)=><article className={`project ${p.accent}`} key={p.title}><div className="project-top"><span>0{i+1}</span><b>{p.tag}</b></div><h3>{p.title}</h3><p>{p.copy}</p><small>{p.impact}</small><div className="arrow">↗</div></article>)}</div></section>
    <CyberSecure360/>
    <section className="section pale" id="credentials"><div className="shell credential-layout"><div><p className="section-no">05 / CREDENTIALS</p><h2>Built on finance. Expanded through technology.</h2><p className="credential-intro">A professional foundation spanning accounting, financial leadership, analytics, audit and cybersecurity governance.</p></div><div className="timeline">{credentials.map(([year,title,place])=><div key={title}><b>{year}</b><section><h3>{title}</h3><p>{place}</p></section></div>)}</div></div></section>
    <section className="section shell skills-wrap"><div><p className="section-no">06 / CAPABILITIES</p><h2>A multidisciplinary toolkit.</h2><p className="credential-intro">Current framework knowledge includes ISO/IEC 27001:2022, NIST CSF 2.0, NIST SP 800-53, COBIT 2019, CIS Controls, PCI DSS and the NIST AI RMF.</p></div><div className="skills">{capabilities.map(s=><span key={s}>{s}</span>)}</div></section>
    <section className="contact" id="contact"><div className="shell contact-inner"><div><p className="section-no light">07 / LET&apos;S CONNECT</p><h2>Looking for leadership grounded in clarity and control?</h2></div><div><p>I welcome conversations about finance leadership, decision support, analytics, cybersecurity governance, institutional transformation and suitable global opportunities.</p><a className="email-address" href="mailto:Kingojoe2000@mail.com">Kingojoe2000@mail.com</a><div className="contact-actions"><a className="button bright" href="mailto:Kingojoe2000@mail.com?subject=Professional%20enquiry%20from%20your%20portfolio">Send an email <b>↗</b></a><a className="button outline-bright" href="https://wa.me/233246153838?text=Hello%20Richmond%2C%20I%20visited%20your%20professional%20portfolio%20and%20would%20like%20to%20connect." target="_blank" rel="noreferrer">WhatsApp</a></div></div></div></section>
    <section className="python-download shell" aria-label="Python portfolio download"><div><span>PY</span><p><strong>Run this portfolio in Python</strong><small>Complete Flask project with instant chat, WhatsApp, email and setup guide.</small></p></div><a className="button code-download" href="/richmond_python_portfolio.zip" download>Download Python code ↓</a></section>
    <footer className="footer shell"><span>© 2026 Richmond Kwadwo Sarpong</span><span>Finance · Analytics · Cybersecurity GRC</span><a href="#top">Back to top ↑</a></footer><ChatBox/><WhatsAppButton/><EmailButton/>
  </main>;
}
