"use client";
import { FormEvent, useEffect, useState } from "react";
type Evidence={id:string;filename:string;controlRef:string;status:string;sha256:string;createdAt:string};
const checks=[["MON-01","8.4.2","Identity provider","MFA coverage","Pass","100% protected"],["MON-02","6.3.3","Vulnerability scanner","Critical patch SLA","Alert","2 overdue assets"],["MON-03","11.6.1","Browser monitor","Payment-page change detection","Pass","No unauthorized change"],["MON-04","10.4.1","SIEM","Daily critical-event review","Pass","Review ticket complete"]];
const connectors=["Microsoft SharePoint","Microsoft OneDrive","ServiceNow GRC","Jira","AWS Security Hub"];
export default function OperationsClient({userEmail,role}:{userEmail:string;role:string}){
 const [evidence,setEvidence]=useState<Evidence[]>([]),[notice,setNotice]=useState(""),[node,setNode]=useState("Payment page"); const canWrite=role!=="Independent Assessor";
 const load=()=>fetch("/api/pci/evidence").then(r=>r.ok?r.json():{evidence:[]}).then(d=>setEvidence(d.evidence||[])).catch(()=>setEvidence([])); useEffect(()=>{load()},[]);
 async function upload(e:FormEvent<HTMLFormElement>){e.preventDefault();setNotice("Securing evidence…");const r=await fetch("/api/pci/evidence",{method:"POST",body:new FormData(e.currentTarget)}),d=await r.json();setNotice(r.ok?`Stored ${d.evidence.filename} with SHA-256 integrity metadata.`:d.error);if(r.ok){e.currentTarget.reset();load()}}
 return <><nav className="ops-nav"><a href="#vault">Evidence vault</a><a href="#monitoring">Monitoring</a><a href="#analysis">AI analysis</a><a href="#connectors">Connectors</a><a href="#scope-map">Scope map</a><a href="../">Public dashboard</a></nav>
 <section className="ops-metrics"><article><span>Authenticated role</span><strong>{role}</strong></article><article><span>Control signals</span><strong>4 live models</strong></article><article><span>Evidence objects</span><strong>{evidence.length}</strong></article><article><span>OSCAL</span><strong>JSON ready</strong></article></section>
 <section className="ops-card" id="vault"><Head no="01" title="Secure evidence vault" copy="R2 object storage with D1 ownership, integrity and review metadata." badge="D1 metadata · R2 objects"/><form className="vault-form" onSubmit={upload}><label>Control reference<input name="controlRef" required placeholder="e.g. 8.4.2"/></label><label>Evidence file<input name="file" type="file" required accept=".pdf,.csv,.txt,.json,.png,.jpg,.jpeg"/></label><button disabled={!canWrite}>{canWrite?"Upload securely":"Write permission required"}</button></form>{notice&&<p className="ops-notice">{notice}</p>}<div className="vault-list">{evidence.length?evidence.map(x=><article key={x.id}><div><b>{x.filename}</b><small>{x.controlRef} · {x.createdAt}</small></div><span>{x.status}</span><code>{x.sha256.slice(0,18)}…</code></article>):<p>No evidence uploaded yet. The protected vault is ready.</p>}</div></section>
 <section className="ops-card" id="monitoring"><Head no="02" title="Continuous control monitoring" copy="Machine signals mapped to PCI DSS control outcomes." badge="Continuous assurance"/><div className="monitor-grid">{checks.map(c=><article key={c[0]} className={c[4].toLowerCase()}><span>{c[0]} · PCI {c[1]}</span><h3>{c[3]}</h3><p>{c[2]}</p><b>{c[4]} · {c[5]}</b></article>)}</div></section>
 <section className="ops-card" id="analysis"><div className="ops-heading"><div><span>03 / CITED AI EVIDENCE ANALYSIS</span><h2>Explainable findings linked to source evidence</h2><p>Grounded portfolio analysis demonstrates citation-first review without transmitting files externally.</p></div><button onClick={()=>location.href="/api/pci/oscal"}>Download OSCAL JSON ↓</button></div><div className="analysis-grid"><article><b>High-confidence finding</b><h3>MFA coverage supports Requirement 8.4.2</h3><p>The identity export indicates complete coverage for modelled CDE access paths.</p><a href="#vault">Citation: EV-015 · MFA coverage export · v3.0</a></article><article className="warning"><b>Evidence gap</b><h3>Payment-page change alert requires test evidence</h3><p>The control is configured, but an attributable alert test must be retained.</p><a href="#vault">Citation: EV-022 · Requirement 11.6.1</a></article></div></section>
 <section className="ops-card" id="connectors"><Head no="04" title="Real connector architecture" copy="Server-side OAuth adapters, scoped clients, verified webhooks, retries and audit events. Connections await owner authorization." badge="OAuth-ready · disconnected"/><div className="adapter-grid">{connectors.map((name,i)=><article key={name}><span>ADAPTER 0{i+1}</span><h3>{name}</h3><p>OAuth callback · scoped API client · retry queue · webhook verification</p><button disabled>Owner authorization required</button></article>)}</div></section>
 <section className="ops-card" id="scope-map"><Head no="05" title="Interactive PCI scope map" copy="Select a system to inspect its PCI scope impact and trust relationship." badge={node}/><div className="scope-layout"><div className="scope-flow">{["Customer browser","Payment page","Hosted payment fields","Payment gateway","Fraud telemetry","SIEM"].map((n,i)=><span key={n}><button onClick={()=>setNode(n)}>{n}</button>{i<3&&<i>→</i>}</span>)}</div><aside><span>SELECTED SYSTEM</span><h3>{node}</h3><p>{node==="Payment gateway"?"TPSP: current AOC and shared-responsibility evidence required.":node==="SIEM"?"Connected-to security system supporting Requirements 10 and 12.":"In scope or security-impacting; changes require authorization, monitoring and evidence."}</p></aside></div></section></>;
}
function Head({no,title,copy,badge}:{no:string;title:string;copy:string;badge:string}){return <div className="ops-heading"><div><span>{no} / V4 CAPABILITY</span><h2>{title}</h2><p>{copy}</p></div><b>{badge}</b></div>}
