(() => {
  const roles={"Program Administrator":["Manage users","Configure connectors","Edit controls","Approve evidence","Export reports"],"Compliance Manager":["Edit controls","Approve evidence","Schedule reminders","Export reports"],"Control Owner":["Upload evidence","Update assigned controls","Respond to reminders"],"Independent Assessor":["Review evidence","Record findings","Export reports"],"Executive Viewer":["View dashboards","Export reports"]};
  const audit=[["AUD-1008","2026-08-21 15:42","A. Mensah","Approved evidence","EV-019","9df1…bc20","34fa…c772"],["AUD-1007","2026-08-21 14:10","K. Owusu","Updated control status","10.4.1","128c…90a1","9df1…bc20"],["AUD-1006","2026-08-21 11:25","System","Evidence reminder issued","EV-012","c880…182e","128c…90a1"],["AUD-1005","2026-08-20 17:03","R. Sarpong","Rejected evidence","EV-006","genesis","c880…182e"]];
  const reminders=[["Evidence expires in 30 days","Evidence owner + Compliance","Email + dashboard","2026-09-01"],["Remediation due in 14 days","Control owner","Email","2026-08-31"],["TRA review due in 45 days","Risk owner + Approver","Dashboard","2026-09-15"],["TPSP assurance expires in 60 days","Vendor Risk Lead","Email + dashboard","2026-09-01"]];
  const connectors=[["CON-01","Microsoft SharePoint","Document repository","PCI Evidence Library","Connected","2026-08-21 14:30"],["CON-02","Microsoft OneDrive","Evidence intake","Control Owner Uploads","Connected","2026-08-21 13:15"],["CON-03","ServiceNow GRC","Control and finding exchange","PCI Assessment","Ready","Not run"],["CON-04","Jira","Remediation tickets","PCI-DSS project","Connected","2026-08-21 15:00"],["CON-05","AWS Security Hub","Technical evidence feed","CDE findings","Ready","Not run"]];
  const esc=v=>String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
  const role=document.querySelector("#staticRole"); role.innerHTML=Object.keys(roles).map(r=>`<option>${r}</option>`).join("");
  function renderRole(){const active=role.value;document.querySelector("#staticRoleName").textContent=active;document.querySelector("#staticPermissions").innerHTML=roles[active].map(p=>`<b>✓ ${esc(p)}</b>`).join("");document.querySelector("#staticRoleList").innerHTML=Object.entries(roles).map(([r,p])=>`<div class="${r===active?"active":""}"><strong>${esc(r)}</strong><small>${p.length} permissions</small></div>`).join("");document.querySelectorAll(".connector-card button").forEach(b=>{b.disabled=!roles[active].includes("Configure connectors");b.textContent=b.disabled?"Admin permission required":"Run test sync"});document.querySelector("#runReminders").disabled=!(roles[active].includes("Schedule reminders")||active==="Program Administrator")}
  role.addEventListener("change",renderRole);
  document.querySelector("#staticAudit").innerHTML=audit.map(e=>`<div><i></i><span><b>${e[0]} · ${e[3]}</b><small>${e[1]} · ${e[2]} · ${e[4]}</small><code>${e[5]} → ${e[6]}</code></span></div>`).join("");
  document.querySelector("#staticReminders").innerHTML=reminders.map(r=>`<div><span><b>${r[0]}</b><small>${r[1]} · ${r[2]}</small></span><em>${r[3]}</em></div>`).join("");
  document.querySelector("#staticConnectors").innerHTML=connectors.map(c=>`<div class="connector-card"><div><span>${c[0]}</span><b class="${c[4].toLowerCase()}">${c[4]}</b></div><h3>${c[1]}</h3><p>${c[2]}</p><dl><div><dt>Mapping</dt><dd>${c[3]}</dd></div><div><dt>Last sync</dt><dd class="sync-value">${c[5]}</dd></div></dl><button>Run test sync</button></div>`).join("");
  document.querySelectorAll(".connector-card button").forEach(b=>b.addEventListener("click",()=>{b.closest(".connector-card").querySelector(".sync-value").textContent="Simulation completed just now"}));renderRole();
  document.querySelector("#runReminders").addEventListener("click",()=>document.querySelector("#reminderResult").textContent="Simulation complete — 7 notifications queued, 0 delivery failures");document.querySelector("#printReport").addEventListener("click",()=>window.print());
  const downloads={audit:[["Event ID","Timestamp","Actor","Action","Object","Previous Hash","Event Hash"],...audit],controls:[["Requirement","Control","Owner","Status"],["1.2.7","Network security reviews","Network Security","Implemented"],["6.4.3","Payment-page scripts","Application Security","Partial"],["12.8.5","TPSP responsibility","GRC","Implemented"]],evidence:[["Evidence ID","Requirement","Owner","Freshness"],["EV-001","1.2.7","Network Security","Current"],["EV-005","6.4.3","Application Security","Expired"],["EV-008","12.8.5","GRC","Due Soon"]]};
  document.querySelectorAll("[data-export]").forEach(b=>b.addEventListener("click",()=>{const name=b.dataset.export,csv=downloads[name].map(row=>row.map(v=>`"${String(v).replaceAll('"','""')}"`).join(",")).join("\n"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([csv],{type:"text/csv"}));a.download=`pci-dss-${name}-export.csv`;a.click();URL.revokeObjectURL(a.href)}));
})();
